apiVersion: v1
kind: ServiceAccount
metadata:
  name: iwo-user
{{- if eq .Values.roleName "iwo-cluster-reader" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iwo-cluster-reader
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - nodes
      - pods
      - deployments
      - replicasets
      - replicationcontrollers
      - services
      - endpoints
      - namespaces
      - limitranges
      - resourcequotas
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - nodes/spec
      - nodes/stats
    verbs:
      - get
{{- end }}
{{- if eq .Values.roleName "iwo-cluster-admin" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iwo-cluster-admin
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - nodes
      - pods
      - deployments
      - replicasets
      - replicationcontrollers
    verbs:
      - '*'
  - apiGroups:
      - ""
      - apps
      - extensions
      - policy
    resources:
      - services
      - endpoints
      - namespaces
      - limitranges
      - resourcequotas
      - daemonsets
      - persistentvolumes
      - persistentvolumeclaims
      - poddisruptionbudget
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes/spec
      - nodes/stats
    verbs:
      - get
{{- end }}
---
kind: ClusterRoleBinding
# For OpenShift 3.4-3.7 use apiVersion: v1
# For kubernetes 1.9 use rbac.authorization.k8s.io/v1
# For kubernetes 1.8 use rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iwo-all-binding
subjects:
  - kind: ServiceAccount
    name: iwo-user
    namespace: {{ .Release.Namespace }}
roleRef:
  # User creating this resource must have permissions to add this policy to the SA
  kind: ClusterRole
  # accepted values cluster-reader disc and monitoring.
  name: {{ .Values.roleName }}
  # For OpenShift v3.4 remove apiGroup line
  apiGroup: rbac.authorization.k8s.io